[functions]
  directory = "functions" # netlify-lambda builds to this folder AND Netlify reads functions from here
[build]
  functions = "functions"
  publish = "build"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200